### ISSUE TITLE
Kiwix macOS DMG download is broken

### ISSUE THREAD

**Issue by kelson42** [offspot/demo#12]
<img width="1080" alt="image" src="https://github.com/offspot/demo/assets/1029718/673b9ce9-14e2-4973-bd64-d2b1cbdeea3c">

**Comment by rgaudin** [comment]
Thank you ; I'm closing without a fix.

- demo image was created when we were including 3.1.0 for macOS.
- we're now including 3.3.0
- we change the URL format (folder and filename) for macOS dmg downloads
- We decided not to support the old format anymore (except for the latest permalink)
- this only affects images created before 3.3.0… and **using the beta dashboard**.

I think we can live we the online demo as it is and wait for next month update ; but we can regen is you want to _validate_ it.

**Comment by kelson42** [comment]
Still unsure if this is a demo problem or an image problem.

I think that if we achieve to create images with this kind of 404 then this is a bug. If the targeted dmg can not be downloaded and integrated in the image, the imager should stop or print a big error.

**Comment by rgaudin** [comment]
Ah thank you for your insistance, there's indeed an issue: https://github.com/offspot/offspot-config/issues/44

Below is my original response

---
> Still unsure if this is a demo problem or an image problem.

It's both but it's mostly an image problem
When the image is created, it is passed an URL and that URL is downloaded and stored on the disk. Should the URL not be OK, image fails to create.

For that specific image, at time of creation (May 1st), we had:

```yaml
- to: /data/contents/zims/kiwix-desktop-macos_3.1.0.dmg
  url: https://mirror.download.kiwix.org/release/kiwix-desktop-macos/kiwix-desktop-macos_3.1.0.dmg
  via: direct
  size: 16051402
  checksum:
    algo: md5
    value: 747fd0841b56d2d5158e0e65646b1be1
    kind: digest
```

That's for the _it's image-related_: 3.1.0 link is written inside the image.

Now in a hotspot configuration, that's not an issue because the file would be served locally. On the demo, we [rewrite the URL to use the online domain](https://github.com/offspot/demo/blob/main/src/offspot_demo/prepare.py#L100)

---

And that's where I realized rewritten URL would not look at all like this download link and is still served _locally_ by the demo. I'll keep this closed in favor of the offspot-config one
